version: '3.3'

services:
  stable-diffusion:
    image: "litty-llm"
    container_name: litty-llm
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - ../logs:/logs
      - ../checkpoints:/checkpoints
      - conda_env:/opt/conda
      - root_profile:/root
    ports:
      - "127.0.0.1:5555:5555"
volumes:
  conda_env:
  root_profile:
