name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchvision=0.13.1
  - numpy=1.23.1
  - pip:
      - torch>=2.0.0
      - lightning>=2.0.0
      - sentencepiece
      - tqdm # convert_checkpoint.py
      - jsonargparse[signatures] # generate.py, convert_checkpoint.py CLI
      - bitsandbytes # quantization.py
      - safetensors==0.2.7
